name: Create changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''
      commit:
        description: 'From commit'
        required: true
        default: ''

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate changelog
        uses: dlavrenuek/conventional-changelog-action@v1.1.0
        id: changelog
        with:
          from: ${{ github.event.inputs.commit }}
          to: HEAD
          config-file: "${{ github.workspace }}/.github/workflows/defaultChangelogConfig.json"

      - name: Append to CHANGELOG.md
        run: |
          printf '# %s\n%s\n%s\n' "${{ github.event.inputs.version }}" "${{ steps.changelog.outputs.body }}" "$(cat ./CHANGELOG.md)" > ./CHANGELOG.md

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG.md
